### ISSUE TITLE
Script carries outdated file downloading code.

### ISSUE THREAD

**Issue by ContinualDissapointment** [Sterbweise/T5Server#1]
``` 
 # Download Game File
    cd $HOME/T5Server/
    wget https://plutonium.pw/pluto_t5_full_game.torrent
    tmpfile=$(mktemp)
    chmod a+x $tmpfile
    echo "killall transmission-cli" > $tmpfile
    transmission-cli -f $tmpfile pluto_t5_full_game.torrent -w $HOME/T5Server
```
These online paths no longer work and the script does not have any feedback for their failure. I also noticed that several additional steps do not parse afterwards such as chmod +x on the .sh files.

**Comment by Sterbweise** [comment]
Hello, sorry for the late response. I hope you were able to install the game files in another way. Plutonium has indeed removed the public download of the game's binary files. I’ve made a modification (it's not permanent), but it should work for a while.
